spring:
  application:
    name: ${SPRING_APPLICATION_NAME:student-service}

  datasource:
    url: jdbc:mysql://localhost:3306/student_service?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Alina@17
    validation-query: SELECT 1
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
#        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 1234
  servlet:
    context-path: /student-service
